-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MIPS_tester IS
   PORT (
		reset, clock										: OUT STD_LOGIC; 
		BPADD_input											: OUT STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		
		PC_out												: IN STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		read_data_1_ID_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		read_data_2_ID_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		write_data_ID_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );	
     	Branch_ID_out										: IN STD_LOGIC;
		Instruction_ID_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		RegWrite_ID_out										: IN STD_LOGIC;
		Instruction_EX_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ALU_result_EX_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ALU_Ainput_EX_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ALU_Binput_EX_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		Zero_EX												: IN STD_LOGIC;
		Instruction_MEM_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		MemWrite_MEM_out									: IN STD_LOGIC;
		write_data_MEM_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		read_data_MEM_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		address_MEM_out										: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );	
		instruction_WB_out									: IN STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		MemtoReg_WB_out										: IN STD_LOGIC;
		CLKCNT_out											: IN STD_LOGIC_VECTOR( 15 DOWNTO 0 );
		STCNT_out											: IN STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		FHCNT_out											: IN STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		STtrigger											: IN STD_LOGIC
		);

-- Declarations

END MIPS_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MIPS_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 100000 us;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   reset <= mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '0',
         '1' AFTER 20 ns,
         '0' AFTER 120 ns;
      WAIT;
    END PROCESS u_1pulse_proc;

   -- Instance port mappings.

END struct;
