onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/reset
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/clock
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/KEY1
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/KEY2
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/KEY3
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/SW
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/LEDR
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/HEX0_out
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/HEX1_out
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/HEX2_out
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/HEX3_out
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/HEX4_out
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/HEX5_out
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/out_signal
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/mw_U_0clk
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/mw_U_0disable_clk
add wave -noupdate -group fpga_TB -radix hexadecimal /fpga_tb/mw_U_1pulse
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/reset
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/clock
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/KEY1
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/KEY2
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/KEY3
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/SW
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX0_out
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX1_out
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX2_out
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX3_out
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX4_out
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX5_out
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/LEDR
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/out_signal
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX0
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX1
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX2
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX3
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX4
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/HEX5
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/KEY1_revr
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/KEY2_revr
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/KEY3_revr
add wave -noupdate -group fpga_conc -radix hexadecimal /fpga_tb/U_0/reset_revr
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/reset
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/clock
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/SW
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY1
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY2
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY3
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/HEX0
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/HEX1
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/HEX2
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/HEX3
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/HEX4
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/HEX5
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/LEDR
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/out_signal
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/MemWrite_out
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/MemRead_out
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/TYPE_reg
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/data
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/address
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/INTR
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/INTA
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/GIE
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY1_int
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY2_int
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY3_int
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/BT_int
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY1_fb
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY2_fb
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/KEY3_fb
add wave -noupdate -group TOP -radix hexadecimal /fpga_tb/U_0/U_0/BT_fb
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/reset
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/clock
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/INTR
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/TYPE_reg
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/data
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/address
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/INTA
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/GIE
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MemRead_out
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Memwrite_out
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ret_add_int
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/PC_plus_4
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/read_data_1
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/read_data_2
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Sign_Extend
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Add_result
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ALU_result
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/read_data
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ALUSrc
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Branch
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/BranchNE
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/jump
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/RegDst
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Regwrite
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Zero
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MemWrite
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MemtoReg
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MemRead
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/JumpAL
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/sft16
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ALUop
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/Instruction
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/inst_j
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/jr
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/PC
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/pc_inter
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/INTR1
add wave -noupdate -group MIPS -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/INTR2
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/Opcode
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/clock
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/reset
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/INTR
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/RegDst
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/ALUSrc
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/MemtoReg
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/RegWrite
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/MemRead
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/MemWrite
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/Branch
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/BranchNE
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/jump
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/jumpAL
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/ALUop
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/INTA_out
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/INTR1_out
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/INTR2
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/R_format
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/Lw
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/Sw
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/mul
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/beq
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/bne
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/addi
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/andi
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/ori
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/xori
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/slti
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/lui
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/j
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/jal
add wave -noupdate -group CONTROL -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/CTL/INTR1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/Add_result
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/Branch
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/BranchNE
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/jump
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/jr
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/Zero
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/clock
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/reset
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/read_data_1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_j
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/pc_inter
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/INTR2
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/PC_out
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/Instruction
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/ret_add_int
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/PC_plus_4_out
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/PC
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/PC_plus_4
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/next_PC
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/Mem_Addr
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/next_PC_3
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/next_PC_2
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/next_PC_1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/PCSrc
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/wren_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/wren_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/rden_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/rden_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/data_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/data_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/address_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/address_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/clock0
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/clock1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/clocken0
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/clocken1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/clocken2
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/clocken3
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/aclr0
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/aclr1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/addressstall_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/addressstall_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/byteena_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/byteena_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/q_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/q_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/eccstatus
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_data_reg_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_data_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_reg_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp2_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp_wren_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp2_wren_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp_wren_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_tmp2_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_output_latch
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_ecc_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_q_ecc_tmp_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_current_written_data_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_original_data_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_original_data_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_a_x
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_b_x
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_a_out
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_b_out
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_a_out_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_mask_reg_b_out_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_address_reg_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_address_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_wren_reg_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_wren_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_rden_reg_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_rden_reg_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_read_flag_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_read_flag_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_reread_flag_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_reread_flag_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_reread_flag2_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_reread_flag2_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_write_flag_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_write_flag_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_nmram_write_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_nmram_write_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_indata_aclr_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_address_aclr_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_wrcontrol_aclr_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_indata_aclr_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_address_aclr_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_wrcontrol_aclr_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_outdata_aclr_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_outdata_aclr_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_rdcontrol_aclr_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_aclr_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_byteena_aclr_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/good_to_go_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/good_to_go_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_core_clocken_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_core_clocken_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_core_clocken_b0
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_core_clocken_b1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_inclocken0
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_input_clocken_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_outdata_clken_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_outdata_clken_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_outlatch_clken_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_outlatch_clken_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_core_clocken_a_reg
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_core_clocken_b_reg
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/default_val
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_data_zero_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_data_zero_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_data_ones_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_data_ones_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/same_clock_pulse0
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/same_clock_pulse1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_force_reread_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_force_reread_a1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_force_reread_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_force_reread_b1
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_force_reread_signal_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_force_reread_signal_b
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_good_to_write_a
add wave -noupdate -group IFETCH -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/IFE/inst_memory/i_good_to_write_b
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/Instruction
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/read_data
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/ALU_result
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/RegWrite
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/MemtoReg
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/RegDst
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/JumpAL
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/pc_plus_4
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/ret_add_int
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/clock
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/reset
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/INTR
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/jr
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/INTR1
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/read_data_1
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/read_data_2
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/Sign_extend
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/sft16
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/inst_j
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/GIE
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/pc_inter
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/register_array
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/write_register_address
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/result
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/write_data
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/read_register_1_address
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/read_register_2_address
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/write_register_address_1
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/write_register_address_0
add wave -noupdate -group IDECODE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/ID/Instruction_immediate_value
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Read_data_1
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Read_data_2
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Sign_extend
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/ALUOp
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/ALUSrc
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Zero
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/ALU_Result
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Add_Result
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/jr
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/PC_plus_4
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/sft16
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/clock
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/reset
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Ainput
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Binput
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/ALU_output_mux
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Branch_Add
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/ALU_ctl
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shift_res
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shamt
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/Function_opcode
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shift/dir
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shift/x
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shift/y
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shift/res
add wave -noupdate -group EXECUTE -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/EXE/shift/res_mat
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/ALU_result
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/read_data_2
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/MemRead
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/Memwrite
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/clock
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/reset
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/INTR1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/TYPE_reg
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/read_data_out
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/address_out
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/write_clock
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/bus_write_en
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/bus_read_en
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/read_data
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/memwrite_dm
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/Mem_Addr
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/address
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/write_data
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/wren_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/wren_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/rden_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/rden_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/data_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/data_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/address_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/address_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/clock0
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/clock1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/clocken0
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/clocken1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/clocken2
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/clocken3
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/aclr0
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/aclr1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/addressstall_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/addressstall_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/byteena_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/byteena_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/q_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/q_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/eccstatus
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_data_reg_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_data_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_reg_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp2_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp_wren_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp2_wren_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp_wren_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_tmp2_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_output_latch
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_ecc_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_q_ecc_tmp_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_current_written_data_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_original_data_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_original_data_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_a_x
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_b_x
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_a_out
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_b_out
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_a_out_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_mask_reg_b_out_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_address_reg_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_address_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_wren_reg_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_wren_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_rden_reg_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_rden_reg_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_read_flag_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_read_flag_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_reread_flag_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_reread_flag_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_reread_flag2_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_reread_flag2_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_write_flag_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_write_flag_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_nmram_write_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_nmram_write_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_indata_aclr_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_address_aclr_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_wrcontrol_aclr_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_indata_aclr_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_address_aclr_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_wrcontrol_aclr_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_outdata_aclr_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_outdata_aclr_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_rdcontrol_aclr_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_aclr_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_byteena_aclr_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/good_to_go_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/good_to_go_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_core_clocken_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_core_clocken_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_core_clocken_b0
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_core_clocken_b1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_inclocken0
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_input_clocken_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_outdata_clken_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_outdata_clken_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_outlatch_clken_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_outlatch_clken_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_core_clocken_a_reg
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_core_clocken_b_reg
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/default_val
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_data_zero_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_data_zero_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_data_ones_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_data_ones_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/same_clock_pulse0
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/same_clock_pulse1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_force_reread_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_force_reread_a1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_force_reread_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_force_reread_b1
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_force_reread_signal_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_force_reread_signal_b
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_good_to_write_a
add wave -noupdate -group DMEMORY -radix hexadecimal /fpga_tb/U_0/U_0/MIPS_entity/MEM/data_memory/i_good_to_write_b
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/clock
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/reset
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/address
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/GIE
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/MemRead
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/MemWrite
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/data
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/clr_irq
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/BT_int
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/KEY1_int
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/KEY2_int
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/KEY3_int
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/INTR_out
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/KEY1_fb
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/KEY2_fb
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/KEY3_fb
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/BT_fb
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/TYPE_reg
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/IE_reg
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/IFG_reg
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/irq
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/INTR
add wave -noupdate -group INT_CTL -radix hexadecimal /fpga_tb/U_0/U_0/INT_CTL_entity/top_priority
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/SW
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY1
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY2
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY3
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/Address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY1_fb
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY2_fb
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY3_fb
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX0
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX1
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX2
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX3
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX4
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX5
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LEDR
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY1_int
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY2_int
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/KEY3_int
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/SW_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/LED_R/Q
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_0/Q
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_1/Q
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_2/Q
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_3/Q
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_4/Q
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/data
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/MemRead
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/MemWrite
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/address
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/GPO_out
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/write_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/read_en
add wave -noupdate -group GPIO -radix hexadecimal /fpga_tb/U_0/U_0/GPIO_entity/HEX_5/Q
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/MCLK
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/reset
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BT_fb
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/data
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/address
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/MemWrite
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BT_int
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/out_signal
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTCTL
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTCNT
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/out_conter
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTCCR0
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTCCR1
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTCL0
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTCL1
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/CLK
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/MCLK2
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/MCLK4
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/MCLK8
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTOUTEN
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTHOLD
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTSSEL
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/BTIPx
add wave -noupdate -group timer -radix hexadecimal /fpga_tb/U_0/U_0/timer_entity/set_BTIFG
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {294061 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 265
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {452040 ps}
